B1anc0N1n0/SDG_Discord_Bot_Original

SDGDiscordBot.js

Super minor, but may as well standardize this. All strings in Javascript can be either single or double quoted, but as most the project is in double we should stay consistent.

Standardize Double vs Single Quotes

---

SDGDiscordBot.js

Will provide token on server directly for now

Change authentication method to use a bot token

---

SDGDiscordBot.js

This was found in PR https://github.com/B1anc0N1n0/SDG_Discord_Bot/pull/12 when the response also included the trigger making for some interesting (see: infinite loop) behavior.

Bot should ignore all message generated from itself

---

SDGDiscordBot.js

this should help bridge tiny network issues on our or discords side along with logging it when it happens.

AutoReconnect and Logging 

---

RPSManager.js
SDGDiscordBot.js

In doing so, also fixed a crash due to the bot not being ininitialized prior to passing it into the RPS Manager

Added the ability to play RPS vs the Bot. 

---

README.md

Just updating the README to reflect some of the changes and gotcha's for getting up and running.

Updating the Shamebot README

---

SDGDiscordBot.js
modules/informationModule.js

Example Data
```
Here are your full stats as requested:
Servers:
Test Server
Channels:
general,General,test
Users:
Frost-test-bot#6086,DeaconnFrost#5626,DaKing#2377,ShameBot#2850,ShameBotTest - Blanco#6084
```

Bot stats - Simple and Full commands

---

SDGDiscordBot.js

This will finish off number 8 in #15 "Conform to Discord Guidelines" re responding to other bots messages.
In this example you can see my test bot ignoring the Shamebot's response whereas Shamebot responded to the test bot using actual commands in its help response.

Check to see if message is from a bot - if it is ignore it

---

SDGDiscordBot.js

Doesn't do much in the way of error handling, but wanted to see if this worked with an appropriately set up MongoDB. Feel free to pull it into your own separate branch and see if it works.

Assignment, viewing, and clearing of Steam IDs. Top 10 Games Played by Hours Played

---

SDGDiscordBot.js

This code should fix issue #43 and #46. Please code review and merge if appropriate.

Bug fixes and enhancements

---

SDGDiscordBot.js

Wrote mongoDB connection pooling into current code.

Mongo db connection pooling

---

README.md
SDGDiscordBot.js
modules/RPSManager.js
modules/informationModule.js
modules/memeRepliesModule.js
modules/tableCatcherModule.js
modules/winstonModule.js

Moved Winston into it's own module. Added function to create a directory for /logs if it doesn't exist. Added winston support into each module meaning it can be used everywhere now. Updated readme. Updated !help command.

Modularize winston

---

SDGDiscordBot.js
modules/informationModule.js

For the record I know my commits suck ass and I'm a little tipsy. I thought I would troll with my commit messages, wanted to change them, then couldn't figure it out. So here it is. This code allows one to issue the command !setPCBuild _PERMALINK_ to associate a PCpartpicker.com build with their Discord ID. Then they can use !PCBuild _@user_ to get said build.

Pc part picker web scraper

---

package.json

Added dependency for 'cheerio' and 'request' as the new pcpartpicker pc build feature requires these.

Added dependency for 'cheerio' and 'request'

---

SDGDiscordBot.js

Fixed an else statement which was causing the bot to crash if !PCBuild was run on a user who didn't set a build yet.

Fixed an else statement which was causing the bot to crash

---

SDGDiscordBot.js

Added support for custom components added a header that includes power draw, build URL, and time updated.

Pc build tweaks

---

SDGDiscordBot.js
modules/serverLogModule.js

Also fixes pinned message/embedded content false positives.

More server logging handling

---

SDGDiscordBot.js
modules/RPSManager.js
modules/informationModule.js
modules/memeRepliesModule.js
modules/serverLogModule.js
modules/tableCatcherModule.js
package.json

Upgrade complete
run "npm install discord.js --save"
and "npm install"
Ignore warnings about dependancies -> this is the library devs comment, not my own. :P
We will also have to upgrade the server to node v6

Discord JS v9 -> 11 upgrade!

---

modules/RPSManager.js
modules/informationModule.js
modules/memeRepliesModule.js
modules/serverLogModule.js
package.json

We should take stock of the other modules and see if any upgrades are needed/warranted. 
logs, DB, features all look stable to me

Discord JS v11 -> 11.2 upgrade

---

SDGDiscordBot.js
modules/memeRepliesModule.js

Adding bot presence status for meme replies

---

SDGDiscordBot.js
modules/informationModule.js

As requested by members:
!gif HELLO THERE
Will return the first result from giphy, also properly sanitizes the search terms for URL encoding (inclusive of emojis)
I generated a Giphy API token that I will toss on the bot after this is merged. (not something we want in source control so it will sit alongside the other keys in auth.json)

Requested Feature: BetterBot TM Gif Search

---

README.md
modules/informationModule.js
package-lock.json
package.json

Just updating the readme and adding in a package-lock file from the npm update

General Housekeeping: Updating package file and readme

---

SDGDiscordBot.js

Old code wasn't expressly using the array

Simple update of message mentions array usage, was broken

---

package-lock.json
package.json

Update Discord.js to v11.3.2 bug/security fixes
